.devcontainer/compose.yml

Removed port assignment in compose.yml, so that Devcontainer runs properly.
This PR could conceivably go into `main`, but for ease of branch management, I'm opting to put this into `staging`.

fix(docker): do not assign port

---

.devcontainer/devcontainer.json
.vscode/settings.json

* Default to tabsize 2 for all files
* Associate `*.html` with the Liquid plugin for better formatting/syntax highlighting
* Clean up devcontainer config syntax

Chore: minor devcontainer cleanups

---

src/_layouts/default.html
src/index.html
src/stylesheets/main.css

closes #123 
- Removes use of `<article>`. 
- Deletes `article` CSS.
- Uses `<main class="container">` in `default.html` layout instead. All pages should now use `<section class="row">` and `<div class="col-6">` syntax logic.
- Removes use of `class="constricted"` and replaces it with `row/col/justify-center`
- Deletes `.constricted` CSS.
- Refactor out CSS Grid from Footer, Header (to come in #122), and any other homepage content sections (beyond the "constricted" style)
Note: This header top issue will be fixed in #122

Refactor: Use Bootstrap container, remove article & constricted

---

src/_layouts/default.html

Bootstrap JS and CSS should both be at Bootstrap@5.2.3.

fix(default): use Bootstrap@5.2.3

---

src/stylesheets/main.css

closes #138 
- Adds the following Colors and Font Family variables
- The `--bs` prepended variables override Bootstrap variables
- The `--calitp` prepended variables are from the Cal-ITP Figma boards, and are used across the CSS
- Refactor: Going to be using RBG from here on out, for reasons listed below 
```
:root {
--bs-font-sans-serif: "Poppins", system-ui, -apple-system, "Segoe UI", "Roboto", "Helvetica Neue", "Noto Sans",
"Liberation Sans", Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";
--calitp-headline-sans-serif: "Raleway", system-ui, -apple-system, "Segoe UI", "Roboto", "Helvetica Neue", "Noto Sans",
"Liberation Sans", Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";
}
body { …
```

Refactor: Use CSS Variables for colors, font family

---

src/_includes/article.html
src/_includes/articles.html
src/_includes/initiatives.html
src/_includes/rounded.html
src/index.html
src/press.html
src/resources.html
src/stylesheets/main.css

closes #107 
closes #105 
- This PR does not have the Filter bubbles, but it has everything else.
- Rhombus! Rhombus is now only on window size over 992px.
- Creates 2 includes for the style and logic of showing items, showing `Show more` after 6 items
- Adds a few CSS utility classes, variables

Resources, Press pages

---

src/_includes/header.html

closes #158 
- Fixes: `About the project` link
- Fixes: `Reach out` link`
- Click `About the project` from Press and Resources page
- Click `Reach out` link from Press and Resources page, Home page

Fix header's home and reach out links

---

src/index.html
src/stylesheets/main.css

closes #96 
This is the last Rhombus ticket!

Home Page: Convert bottom 2 components to Rhombus on Desktop

---

src/_includes/articles.html
src/press.html
src/resources.html

Adds tabs to Press and Resource pages that contain articles based on tag.
~Note that this PR doesn't have logic to hide the tab with all articles, so it always appears.~ hiding the "all" tab for now
Part of #91 and #92

Feat: article tabs

---

src/_includes/initiatives.html
src/_includes/pills.html
src/press.html
src/resources.html
src/stylesheets/main.css

closes #92 
closes #91 
closes #88 
- Create 2 new CSS classes `black-on-white` and `white-on-color` that governs the colors of Nav Pills
- Use `black-on-white` for home page and `white-on-color` on Press and Resources
- Create `includes` for the Nav Pills on Press and Resources page

CSS for Pills on Resources and Press

---

src/stylesheets/main.css

Closes #168 
Figma shows the padding as `padding: 4px 8px`. Pixels are fine here since we don't need it to grow with the user's default font size.

Fix: pill padding

---

src/_includes/articles.html
src/press.html
src/resources.html

Closes #173 
Moves the filtering logic up to the assignment of the `items` variable. This way the page can check the number of items if it needs to.

Refactor: avoid generating empty sections

---

src/stylesheets/main.css

closes #174 
This PR fixes the rhombus issue on all pages on Safari mobile. Desktop still being investigated and will be fixed in a PR after this.
- Test on Desktop at mobile width
- Test on Mobile Safari with the test Netlify link
- Test on iOS Emulator app on Desktop
- Test home page, press, resources
- Ensure no regressions
All mobile widths (which means mobile width on Desktop too.. and also Safari mobile):

Fix: fix rhombus Safari issue on mobile widths

---

src/_layouts/press.html
src/resources.html
src/stylesheets/main.css

Closes #171 and #172
- makes links on Press Release use same styling as all other links on the site
- makes line break use 40px for top and bottom margins, which is what Figma shows for all line breaks (`hr`)

Fix: Press Release CSS, Resources line break

---

src/stylesheets/main.css

This was a bug I just noticed while testing the app on my phone.
- Bug: On Mobile, the mobile nav links are not vertically centered. I think this was a CSS typo!

fix(mobile): mobile nav link sizing is off, text now vertically centered

---

src/_includes/clipped.html
src/_includes/initiatives.html
src/index.html
src/press.html
src/resources.html
src/stylesheets/main.css

closes #174 fully
- Used https://yoksel.github.io/relative-clip-path/ to create clip-paths directly from svg's from Figma. Tried using https://www.plantcss.com/css-clip-path-generator but the shapes were not coming out the same.
- Avoid use of `filter: url` entirely, b/c it's very buggy on Safari.
- Creates an includes for the Press and Resources SVG, as they use the same one.
- Adds SVGs in-line for all 3 Index page SVGs.
- Adds back box-shadow (using filter) on the bottom 2 rhombuses on Home page (https://css-tricks.com/using-box-shadows-and-clip-path-together/)
- This PR also fixes: the second point on #178
- Apple/Mac OS: test on Safari, Firefox, Chrome for rhombus fixes
- Windows: test on Firefox, Chrome for no regressions
- Android: test on Chrome for no regressions
- iPhone: test …

Fix: Fix Desktop rhombus bug on Safari

---

src/index.html

closes #178 
This PR depends on #188 being closed first.
This PR makes 2 small changes:
1. Add `mb-4` (`margin-bottom: 24px`) to the 1st rhombus. The 2nd rhombus doesn't need any adjustment -- the combination of `align-items-stretch` and the `min-height: 100%` will force the 2nd rhombus to be the same height as the 1st (the taller one).
2. Change `h3` of the 2nd rhombus to match the first's, of `my-4` so that both `h3`'s and the text underneath start at the same vertical height

Fix: Home - Rhombus padding

---

src/_includes/header.html
src/stylesheets/main.css

Closes #180 
OK this definitely feels a little hacky so I am wide open to feedback if there is a better way.
Simply linking to the `#about` section causes the navbar to slightly obscure the header:
Based on a couple of SO posts:
* [Boostrap using fixed navbar and anchor tags to jump to sections](https://stackoverflow.com/a/17181529/453168) which talks about using padding and a corresponding negative margin to avoid the navbar overlap
* [How can I get a negative value of CSS variables](https://stackoverflow.com/a/48639938/453168) which talks about flipping a variable from positive to negative
I added a bit of CSS for this `section#about`, which (I think) gives the intended result:
**Desktop**
**Mobile**

Fix: Make About link jump to About section

---

src/_includes/initiatives.html

Closes #177 
[`b8f5517d`](https://github.com/cal-itp/calitp.org/commit/b8f5517d0bf7f5cbc04e19b4583c57037421c3e6#diff-aa29c099255bf0ab97be6a008965095465c8b9b14edb6865097a7ea026a97c2eR96) added `d-block` to resource links, and this needed to be applied to press links as well.
With `block` display, margin will have effect so we get the 8px from `mb-2`.

Fix: spacing for Initiatives press links

---

src/_includes/footer.html
src/stylesheets/main.css

An assorted mix of footer-related fixes:
1. On your laptop, go to https://staging.calitp.org/press and click **GTFS** or **Benefits** - the footer comes off from the bottom of the page on desktop windows of a certain size. This is because there aren't enough Press release or Articles linked. In the meantime, this PR sets the `main.container` to be at least `calc(100vh - footer height)` so that the footer stays at the bottom.
2. The footer hover color wasn't working b/c of a CSS typo.
3. The spacing of the footer on mobile was a little off.

Fix: Footer issues

---

src/_press/cal-itp-gtfs-schedule-validator.md

closes #179
Adds https://mobilitydata.org/new-web-based-version-of-gtfs-schedule-validator-released/ press release link to GTFS section, as requested by @esquared415

Press: Add new GTFS press release

---

src/_data/initiatives.yml
src/_includes/initiatives.html

fix #208 
- hide Mobi Mart button for GTFS, Benefits
- add pre-button text for Contactless Payments

Fix: Initiatives section

---

.github/workflows/dependabot-differ.yaml

We'll have to update again once https://github.com/cal-itp/calitp.org/issues/80 is closed and the redesign is launched
This is why [this action is failing](https://github.com/cal-itp/calitp.org/actions/workflows/dependabot-differ.yaml) on all the recent PRs

Fix: broken GitHub Action

---

src/_includes/article.html
src/_press/cal-itp-announces-ods.md
src/_press/cal-itp-benefits-launch.md
src/_press/cal-itp-coast-rta-msa.md
src/_press/cal-itp-gtfs-schedule-validator.md
src/_press/cal-itp-payments-data-dashboard.md

closes #207 
- adds `outlet:` key value pair to each Press item, with either `Cal-ITP` for internal press releases or the name of the external media outlet
- show the outlet on the Press page, before the tag and dateline

Press Page: Add Outlet data to press item, show it on press page

---

src/stylesheets/main.css

fix #238 
- Only show the top 3 resources, top 3 press. Up to 3.

Fix: Initiatives - only show top 3 resources, press

---

src/_press/four-northern-california-transit-agencies-join-forces-to-buy-contactless-open-loop-fare-payment-systems-off-of-californias-purchasing-agreements.md

Feat: add press release "Four Northern California..."

---

.github/ISSUE_TEMPLATE/new_press.yml
.github/ISSUE_TEMPLATE/new_resource.yml

They cannot contain boolean values:
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/common-validation-errors-when-creating-issue-forms#bodyi-options-must-not-include-booleans-please-wrap-values-such-as-yes-and-true-in-quotes

Fix: approval field options

---

src/_includes/meta.html
src/index.html
src/press.html
src/resources.html

Use individual page titles/descriptions, update `og` and other `<meta>` tags.
Closes #254

Fix: page metadata

---

src/_includes/meta.html

closes #265
- Add `<link rel="canonical" href="{{ page.url | absolute_url }}" />` set to the absolute URL
Asking social media companies to recognize these calitp.org links!
- https://developers.google.com/search/docs/crawling-indexing/consolidate-duplicate-urls#rel-canonical-link-method
- https://yoast.com/rel-canonical/
> Should a page have a self-referencing canonical URL?
> In the image above, we link the non-canonical page to the canonical version. But should a page set a rel=canonical for itself? This question is a much-debated topic amongst SEOs. At Yoast, we strongly recommend having a canonical link element on every page, and [Google has confirmed that’s best](http://www.thesempost.com/using-rel-canonical-on-all-pages-for-duplicate-content-protection/). That’s because most CMSs …

feat(meta): add self-referential canonical link

---

src/_includes/footer.html
src/_includes/header.html
src/stylesheets/main.css

closes #137 
This PR makes any page on calitp.org more printer-friendly, by having a print mode-specific header, changing the font size and widening the width.
- Print display classes: https://getbootstrap.com/docs/5.2/utilities/display/#display-in-print
- Print display media query: https://developer.mozilla.org/en-US/docs/Web/Guide/Printing
- Use print preview: https://www.sitepoint.com/css-printer-friendly-pages/#testingprinteroutput
- Use DevTools: https://www.sitepoint.com/css-printer-friendly-pages/#testingprinteroutput
- [Cal-ITP and partners celebrate major milestones in implementation of Operational Data Standard (ODS) for transit - Cal-ITP California Integrated Travel Project.pdf](https://github.com/cal-itp/calitp.org/files/12796289/Cal-ITP.and.partners.celebrate.major.milestones. …

Print-friendly site

---

_config.yml
src/_includes/article.html
src/_layouts/resource.html

Closes #267
This PR adds support for hosting Resource pages as HTML. 
To create the `resource` layout, I just copy-and-pasted from the `press` layout, and then I removed some things that don't apply to Resources. I referenced the resource from #266 to see what doesn't apply.
For testing purposes, I made a file at `src/_resources/test.md` with these contents:
```
---
date: "2022-11-01T17:00:00-07:00"
title: |-
this is a test from Angela
category: Case studies
tags:
- Contactless Payments
---
blah blah blah
**bold**
1. apples
1. bananas
1. carrots
```
and here's what it looks like:
Here is what the link to that HTML resource on the Resources page looks like:

Feat: Resources as HTML

---

src/_includes/initiatives.html

fixes #286 
- There are some indentation changes on here, but the only thing I actually added is between Line 102-104: https://github.com/cal-itp/calitp.org/compare/fix/286-home-link-bug?expand=1#diff-aa29c099255bf0ab97be6a008965095465c8b9b14edb6865097a7ea026a97c2eR102-R104
- Adds the same URL logic from the existing Resources page to the homepage, so that links to HTML Resources show up correctly
- Make sure all links in initiatives on the homepage work correctly, esp. the [Fact sheet: Merchant category codes in mobility](http://127.0.0.1:4000/resources/fact-sheet-merchant-category-codes-in-mobility)

fix(homepage): initiatives - fix broken link

---

.github/ISSUE_TEMPLATE/new_resource.yml

closes #275 
Test it out here: https://github.com/machikoyasuda/calitp.org/issues/new?assignees=&labels=content%2Cresources&projects=&template=new_resource.yml&title=New+resource+request

Add file name guidelines to Resources issue template

---

src/_resources/fact-sheet-ods-overview.yml

feat(resources): add overview for gtfs - operational data standard

---

.github/ISSUE_TEMPLATE/new_resource.yml

closes #307 
- changes approval section to ask for approval in Slack
- adds a11y instructions link
- re-orders the questions to be in the same order as how the markdown file asks for them (date, title, asset link, category, tags) -- makes it easier to code the file
I forked the repo and tested out this issue template YML on my fork here: https://github.com/machikoyasuda/calitp.org/issues/new?assignees=&labels=content%2Cresources&projects=&template=new_resource.yml&title=New+resource+request

Update resource issue template

---

.github/CODEOWNERS

Adding @cal-itp/web-review (currently just @mrose914) to `CODEOWNERS` for specific files / directories where the content lives.
This will make it possible to automatically assign review for changes to these files. And means we won't have to wait for another engineer to review simple content updates. Checking with you @mrose914 is that is OK? We typically request your review anyway :sweat_smile:

Feat: web-review team reviews content changes

---

src/_includes/initiatives.html
src/_layouts/default.html
src/scripts/initiatives.js
src/scripts/pill-behavior.js
src/stylesheets/main.css

closes #353 
- Go to http://localhost:4000/#pills-benefits or http://localhost:4000/#pills-benefits - make sure the page loads to the right tab and page height
- Click around other tabs to make sure the other tabs still also open (but the anchor tag in the URL will not change).

Feat: Initiatives by permalink

---

src/stylesheets/main.css

fixes #365 
Updates the primary blue and primary hover blue to colors according to https://github.com/cal-itp/benefits/issues/1423#issuecomment-1601567969
- Links, link hover, menu link, Contact background, Initiatives background, Press background should all be updated.

Update calitp blue and hover blue

---

src/scripts/initiatives.js

Quick follow-up to #363
* Update the URL so it matches the initiative the user is looking at
* Logic that shows a pill's content is now tied to the hash being changed
* Inserts initiative content into user's history
1. Run the app locally
2. Ensure the existing behavior of going directly to e.g. `http://localhost:4000/#initiatives-gtfs` still loads that pill content
3. Change pills
4. Observe the `window.location.hash` value update accordingly
5. Observe the associated pill content become visible
6. Click the back button
7. Observe the previous hash / pill content is visible
<details>
<summary>Loading the page with a hash link</summary>
https://github.com/user-attachments/assets/382b3130-f173-459f-93b0-f68bbaab0a3d
</details>
<details>
<summary>Clicking pills and the back button</summary> …

Refactor: initiative pills change hash

---

src/_includes/clipped-header.html
src/_includes/clipped.html
src/_includes/contact.html
src/_includes/initiatives.html
src/press.html
src/resources.html
src/stylesheets/main.css

closes #375 
This PR is taking a single commit from #364 and teasing out what refactor can be done to the current code, to help #364 and #354 code be cleaner. There are many more custom rhombuses coming up in this current project, and the production code was using the _same_ ID across multiple rhombuses and getting away with it because they were on different pages. This got messy.
This PR:
- Establishes a naming convention for these classes/IDs: `clipped-X` and `path-X`, with an optional `-start` and `-end` suffix for rhombuses that appear in a row as a pair (like the Contact section and future Stats sections)
- Changes Class and ID names - but nothing else. No design should change.
- Ensures there are no class or ID name collisions
How to test:
- Ensure there are no visual regressions on …

Refactor: Rhombus CSS classes

---

src/_includes/styles.html
src/_layouts/default.html
src/robots.txt
src/stylesheet.html
src/stylesheets/main.css

closes #368 
These new styles will be used for both Partners and Customer Stories pages. I have added new code in CSS, but I have not changed any code or designs on the existing pages -- so this is a safe PR to merge b/c no user-facing changes are going into production.
- Upgrade to latest Bootstrap
- Adds some new variable overrides
- Adds new type styles: regular link, blockquote with different color borders, small, stats
- Adds this page https://deploy-preview-371--cal-itp-website.netlify.app/stylesheet to test and document the new styles
- https://deploy-preview-371--cal-itp-website.netlify.app/stylesheet
- No regressions
🟢🟢 Once this PR is reviewed, this PR can be deployed to Production 🟢🟢

CSS: New type styles + docs

---

src/_includes/contact.html
src/stylesheets/main.css

fixes #378 
The contact section's headline font should be:
- 40px on Desktop (a H1 size)
- 32px (which is 2rem) on Mobile (a H2 size)
Creates `h1-md` class which means "this type is h1 size on medium size widths and up".

Contact: Fix headline size

---

src/_includes/contact.html

Fix: Contact area spacing

---

src/index.html

Fix: Home - Desktop - Dot spacing

---

src/_press/cal-itp-benefits-launch.md

closes #390 
Very elegant CSS: https://getbootstrap.com/docs/5.3/helpers/ratio/#example
`aspect-ratio` - on MDN https://developer.mozilla.org/en-US/docs/Web/CSS/aspect-ratio

fix(press): replace GIF with YouTube video

---

README.md

In tandem with this ticket in MobiMart, https://github.com/cal-itp/mobility-marketplace/pull/610/, wanted to use this PR to document:
- calitp.org is NOT sending data to Amplitude.
- calitp.org is being tracked by Google Analytics, version 4, with enhanced measurement turned on for outbound links, file downloads and more.
- adding a note in the README about this so new users know where to look for reporting.

docs: update README with Analytics info

---

.github/scripts/resource-template.py
.github/workflows/resource-template.yml
README.md

There are a few moving parts to this workflow, so let's break them down.
To reduce the number of dependencies we had to worry about in this workflow, I ported the logic found in [GrantBirki/issue-template-parser](https://github.com/GrantBirki/issue-template-parser) into Python so that all the logic fits in this one script. This gives us the added benefit of easily running it locally without the need for emulating a GitHub Actions environment. The debugging functionality and output will behave appropriately when the script is run in a CI environment vs locally.
This script expects a JSON object with the key of `body` as an argument fed via STDIN or as the first argument when running the script. This object shape is used as it is the output of,
```bash
gh issue view <issue num> --json body …
```

Add Python script for generating resource entries

---

src/_press/la-metro-cal-itp-mobility-wallet-prepaid-debit-card-south-la.md

Metro moved their press release and our link broke.
Fixes #452

Chore: update broken press link
