index.html

Closes #19
/cc @esquared415 you can preview the changes here: https://deploy-preview-20--cal-itp-website.netlify.app/ 😄

Content updates for #19

---

README.md
compose.yaml

Closes #23.
Partially addresses #3.

Config for running site locally

---

index.html

Extend market consultation deadline

---

src/stylesheets/main.css

Closes #53 
The fixed footer width was causing a horizontal scrollbar to appear.
_ugh, I guess saving this file also made a bunch of formatting changes... sorry about that_

Fix: horizontal scroll

---

src/gtfs-dashboard
src/gtfs-dashboard.html

Redirect /gtfs-dashboard

---

.gitignore

chore: add .DS_Store ignore for Macs

---

src/_includes/styles.html

Use the same version as MobiMart

Chore: upgrade to full Bootstrap 5.2.3

---

src/index.html

closes #126 
- Delete all the `<p>`s from the numbered section 
- Delete the last number, 5
- Change copy, that will happen in #101 
- Change any CSS/Styles, that will happen in #101

fix(index): delete numbered ps, delete 5

---

src/index.html

closes #129 
- Delete 2 paragraphs
- Updates copy in 1 paragraph
- Change any CSS/styles

Home page: Delete extra grafs from Time is now section

---

_config.yml
src/_includes/date.html
src/_includes/header.html
src/_includes/script_redirect.html
src/_includes/styles.html
src/_layouts/press.html
src/_layouts/redirect.html
src/_press/cal-itp-announces-ods.md
src/_press/cal-itp-benefits-launch.md
src/_press/cal-itp-coast-rta-msa.md
src/_press/cal-itp-payments-data-dashboard.md
src/press.html

Closes #106 
Note I moved the styling of the Press Release list on the landing page to #107 and split out the styling of the Press Release page to #140.

Feat: define Jekyll collection for Press

---

_config.yml
src/_includes/header.html
src/_press/cal-itp-coast-rta-msa.md
src/_resources/case-study-cash-app.md
src/_resources/case-study-contactless-fare-payments.md
src/_resources/fact-sheet-advancing-equity-transit-financial-inclusion.md
src/_resources/fact-sheet-automated-transit-discounts.md
src/_resources/fact-sheet-gtfs-feed.md
src/_resources/fact-sheet-why-go-contactless.md
src/_resources/one-pager-mobility-data-interoperability-principles.md
src/_resources/slide-deck-benefits-overview.md
src/_resources/slide-deck-ca-transit-data-guidelines-draft-v3.0.md
src/_resources/slide-deck-gtfs-wheelchair-accessibility-data.md
src/_resources/slide-deck-understanding-merchant-service-charges.md
src/press.html
src/resources.html

Closes #104 
Like for Press, styling of this landing page is left for #105

Feat: define Jekyll collection for Resources

---

src/_resources/slide-deck-benefits-overview.md

Fix: update Benefits overview resource

---

src/_resources/slide-deck-understanding-merchant-service-charges.md

closes part of #157 
- Removes merchant service charge asset entirely

Fix: Remove merchant service charge

---

src/_includes/footer.html
src/stylesheets/main.css

Part of CSS implementation/refactor

Refactor: Use flexbox for footer, not css grid

---

src/index.html

Home: Rainbow list padding left is 0

---

src/press.html

Fix: Press page CSS

---

src/_includes/initiatives.html

Part of #177 
> center content within the rhombus in Desktop/Tablet

Fix: center Initiatives content

---

src/_includes/initiatives.html
src/stylesheets/main.css

Part of https://github.com/cal-itp/calitp.org/issues/177
> adjust vertical spacing for all sections to 40px Desktop, 28px Mobile

Fix: initiatives sections spacing

---

src/_data/initiatives.yml
src/_press/cal-itp-announces-ods.md
src/_press/cal-itp-benefits-launch.md
src/_press/cal-itp-coast-rta-msa.md
src/_press/cal-itp-payments-data-dashboard.md
src/_resources/case-study-cash-app.md
src/_resources/case-study-contactless-fare-payments.md
src/_resources/fact-sheet-advancing-equity-transit-financial-inclusion.md
src/_resources/fact-sheet-automated-transit-discounts.md
src/_resources/fact-sheet-gtfs-feed.md
src/_resources/fact-sheet-why-go-contactless.md
src/_resources/one-pager-mobility-data-interoperability-principles.md
src/_resources/slide-deck-benefits-overview.md
src/_resources/slide-deck-ca-transit-data-guidelines-draft-v3.0.md
src/_resources/slide-deck-gtfs-wheelchair-accessibility-data.md

closes #157 
closes #179 
https://github.com/cal-itp/calitp.org/issues/179#issuecomment-1592240648

Fix: Copy edits

---

.github/ISSUE_TEMPLATE/new_press.yml

feat: create issue form for Press items

---

src/links.html

Fix: update links redirect

---

src/_resources/case-study-contactless-fare-payments.md

fix(resource): update date

---

src/_includes/initiatives.html

Fixes #229
Applied the fix @machikoyasuda described in https://github.com/cal-itp/calitp.org/issues/229#issuecomment-1665884895

Fix: switching Initiatives on mobile

---

src/_includes/initiatives.html

Initiatives:  Add 16px total vertical padding between links

---

.github/ISSUE_TEMPLATE/new_press.yml
.github/ISSUE_TEMPLATE/new_resource.yml

Feat: issue field to indicate content approval status

---

src/_press/cal-itp-partners-celebrate-major-milestone-implementation-ods.md

Feat: new ODS major milestones press release

---

src/_data/initiatives.yml

Fix: Initiatives - Update copy

---

src/_resources/fact-sheet-merchant-category-codes-in-mobility.md

Feat: add Merchant Category Codes resource

---

src/_resources/one-pager-mobility-data-interoperability-principles.md

Fix: use correct Google Drive link for MDIP resource

---

src/_resources/fact-sheet-enhancing-transit-experience-with-bankon.md

Feat: BankOn fact sheet

---

src/_press/mst-announces-discount-contactless-fares-for-both-local-and-visiting-riders-65.md

Feat: MST Older Adults press release

---

src/_press/mst-veterans-can-now-enjoy-discount-transit-fare-benefit-when-tapping-to-ride-on-monterey-salinas-transit.md

Feat: MST veteran press release

---

.github/ISSUE_TEMPLATE/new_press.yml

Add 2024 for Press issue template

---

src/_resources/fact-sheet-menu-of-services.md

closes #299 
multiple tags works great out of the box!

feat(resources): add fact sheet - cal-itp menu of services

---

src/_resources/fact-sheet-cal-itps-2023-accomplishments.md

Resources: Add Cal-ITP 2023 Accomplishments PDF link

---

src/links.html

Chore: update redirect for Cal-ITP sticker QR code

---

src/_resources/case-study-mobility-rewards-and-loyalty-market-sounding-report.md

Add Rewards & Loyalty case study

---

.devcontainer/postAttach.sh
src/_includes/article.html
src/_resources/case-study-satellite-report.md

Feat: add Satellite Report resource

---

src/_resources/case-study-report-on-transit-technology-ecosystem-with-appendix.md

Feat(resources): report on transit tech ecosystem with appendix

---

.github/workflows/add-to-project-dependencies.yml

Similar to https://github.com/cal-itp/eligibility-server/pull/467

CI: add dependency PRs to project, set status/effort

---

src/_data/initiatives.yml

closes #393 
Add link to homepage in Initiatives section

Home: add Benefits Monthly Newsletter

---

src/_press/sacrts-new-tap2-ride-contactless-payment-system-and-veterans-discount-fare-pilot-program-launching-soon.md

Add SacRT Tap2Ride press release

---

.github/ISSUE_TEMPLATE/new_press.yml
.github/ISSUE_TEMPLATE/new_resource.yml

Chore: add 2025 option to issue templates

---

.github/workflows/resource-slack.yml

This is a straight copy/paste since the functionality required is identical to what already exists.
/cc @thekaveman I need someone with permissions to do the following:
Closes #445

Notify us on Slack on press/resource requests

---

src/_resources/case-study-cal-itp-statewide-fare-guidelines-toolkit.md

Closes #439
Target page: https://deploy-preview-463--cal-itp-website.netlify.app/resources

Auto-PR for Resource Request #439
